Name: Wiser Everywhere
Description: Schedule for Wiser Everywhere
Type: Heating
Monday:
  - Time: 05:30
    Temp: 18.0
  - Time: 07:00
    Temp: 18.5
  - Time: 08:00
    Temp: 19.5
  - Time: 08:30
    Temp: 21.5
  - Time: 20:00
    Temp: 18.0
  - Time: 23:00
    Temp: 17.5
Tuesday:
  - Time: 05:30
    Temp: 18.0
  - Time: 07:00
    Temp: 18.5
  - Time: 08:00
    Temp: 19.5
  - Time: 08:30
    Temp: 21.5
  - Time: 20:00
    Temp: 18.0
  - Time: 23:00
    Temp: 17.5
Wednesday:
  - Time: 05:30
    Temp: 18.0
  - Time: 07:00
    Temp: 18.5
  - Time: 08:00
    Temp: 19.5
  - Time: 08:30
    Temp: 21.5
  - Time: 20:00
    Temp: 18.0
  - Time: 23:00
    Temp: 17.5
Thursday:
  - Time: 05:30
    Temp: 18.0
  - Time: 07:00
    Temp: 18.5
  - Time: 08:00
    Temp: 19.5
  - Time: 08:30
    Temp: 21.5
  - Time: 20:00
    Temp: 18.0
  - Time: 23:00
    Temp: 17.5
Friday:
  - Time: 05:30
    Temp: 18.0
  - Time: 07:00
    Temp: 18.5
  - Time: 08:00
    Temp: 19.5
  - Time: 08:30
    Temp: 21.5
  - Time: 20:00
    Temp: 18.0
Saturday:
  - Time: 03:30
    Temp: 18.5
  - Time: 05:15
    Temp: 18.0
  - Time: 07:00
    Temp: 18.5
  - Time: 08:00
    Temp: 19.5
  - Time: 08:30
    Temp: 21.5
  - Time: 20:00
    Temp: 18.0
  - Time: 23:00
    Temp: 18.5
Sunday:
  - Time: 03:30
    Temp: 18.5
  - Time: 05:15
    Temp: 18.0
  - Time: 07:00
    Temp: 18.5
  - Time: 08:00
    Temp: 19.5
  - Time: 08:30
    Temp: 21.5
  - Time: 20:00
    Temp: 18.0
  - Time: 23:00
    Temp: 18.5
