  default: info
  logs:
    # log level for HA core
    homeassistant.core: info

    # log level for MQTT integration
    homeassistant.components.mqtt: error

    # log level for all python scripts
    homeassistant.components.python_script: info

    # log level for a custom component
    custom_components.my_integration: error

    # log level for the `aiohttp` Python package
    aiohttp: error

    # log level for both 'glances_api' and 'glances' integration
    homeassistant.components.glances: info
    glances_api: error
    
    custom_components.car_wash: debug