
# Use this file to store secrets like usernames and passwords.
# Learn more at https: ""
some_password: ""

db_url: ""

alarm_code: ""

steam_apikey: ""

xiaomi_vacuum_host: ""
xiaomi_vacuum_token: ""
xiaomi_cloud_username: ""
xiaomi_cloud_password: ""

influx_host: ""
influx_username: ""
influx_password: ""

surepet_username: ""
surepet_password: ""

#surepetcare: ""
#  username: ""
#  password: ""
# feeders: ""
#  flaps: ""
#  pets: ""
#  scan_interval: ""
#   97719 Dobby
#   97720 Rolly
#   176721 Rowdy


samsungtv_ip: ""
samsungtv_mac: ""

chrispc_mac: ""
chrispc_ip: ""